# collect_gesture_data.py - Generated by setup
import serial
import csv
import time
from pathlib import Path

ARDUINO_PORT = 'COM6'
BAUD_RATE = 9600
DURATION = 3
SAMPLES_PER_GESTURE = 20
GESTURES = ['rest', 'clench', 'wrist']  # must match csv_loader.py gesture names

Path("data").mkdir(exist_ok=True)

def collect_gesture(gesture_name, sample_num):
    ser = serial.Serial(ARDUINO_PORT, BAUD_RATE)
    ser.reset_input_buffer()
    time.sleep(2)
    
    filename = f"data/data_{gesture_name}_{int(time.time())}.csv"
    
    print(f"\nRecording {gesture_name} (sample {sample_num}/{SAMPLES_PER_GESTURE})")
    print("Get ready... 3... 2... 1... GO!")
    
    data = []
    start_time = time.time()
    
    while time.time() - start_time < DURATION:
        line = ser.readline().decode('latin-1').strip()
        try:
            value = int(line)
            timestamp = time.time()
            data.append([timestamp, value])
        except ValueError:
            continue
    
    with open(filename, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['timestamp', 'value'])
        writer.writerows(data)
    
    print(f"Saved {len(data)} samples to {filename}")
    ser.close()
    time.sleep(1)

def main():
    print("=" * 70)
    print("GESTURE DATA COLLECTION")
    print("=" * 70)
    print(f"\nCollecting {SAMPLES_PER_GESTURE} samples for each of {len(GESTURES)} gestures.")
    print(f"Each sample is {DURATION} seconds long.\n")
    
    input("Press Enter when ready to start...")
    
    for gesture in GESTURES:
        print(f"\n{'-' * 70}")
        print(f"GESTURE: {gesture.upper()}")
        print(f"{'-' * 70}")
        print(f"Instructions: Perform '{gesture}' when recording starts.")
        input("Press Enter to begin...")
        
        for i in range(1, SAMPLES_PER_GESTURE + 1):
            collect_gesture(gesture, i)
            if i < SAMPLES_PER_GESTURE:
                print("\nRelax for 3 seconds...")
                time.sleep(3)
    
    print("\n" + "=" * 70)
    print("DATA COLLECTION COMPLETE!")
    print("=" * 70)
    print(f"\nCollected {SAMPLES_PER_GESTURE * len(GESTURES)} total samples.")
    print("Next step: Train the model with 'python main_train.py'")

if __name__ == '__main__':
    main()
